const OBSERVABILITY = [
  'TRACE', 'SPAN', 'METRIC', 'LOG', 'ALERT',
  'DASHBOARD', 'LATENCY', 'THROUGHPUT', 'ERROR', 'TIMEOUT',
  'SLO', 'SLA', 'SLI', 'UPTIME', 'DOWNTIME',
  'CARDINALITY', 'SAMPLING', 'RETENTION', 'INGESTION', 'PIPELINE',
  'GRAFANA', 'PROMETHEUS', 'DATADOG', 'SPLUNK', 'KIBANA',
  'ELASTICSEARCH', 'FLUENTD', 'JAEGER', 'ZIPKIN', 'TEMPO',
  'LOKI', 'MIMIR', 'CORTEX', 'THANOS', 'VICTORIA',
  'PERCENTILE', 'HISTOGRAM', 'GAUGE', 'COUNTER', 'SUMMARY',
  'HEARTBEAT', 'HEALTHCHECK', 'PROBE', 'ENDPOINT', 'STATUS',
  'INCIDENT', 'RUNBOOK', 'POSTMORTEM', 'ESCALATION', 'ONCALL',
  'PAGER', 'SEVERITY', 'TRIAGE', 'REMEDIATION', 'ROLLBACK',
  'DEPLOY', 'CANARY', 'ROLLOUT', 'FEATURE', 'FLAG',
  'THROTTLE', 'RATELIMIT', 'CIRCUIT', 'BREAKER', 'FALLBACK',
  'RETRY', 'BACKOFF', 'JITTER', 'QUEUE', 'BUFFER',
  'SHARD', 'REPLICA', 'PARTITION', 'CLUSTER', 'NODE',
  'CONTAINER', 'POD', 'NAMESPACE', 'SERVICE', 'MESH',
  'PROXY', 'SIDECAR', 'INGRESS', 'EGRESS', 'LOAD',
  'BALANCER', 'CACHE', 'REDIS', 'KAFKA', 'RABBIT',
  'GRPC', 'REST', 'GRAPHQL', 'WEBHOOK', 'POLLING',
  'BATCH', 'STREAM', 'EVENT', 'PAYLOAD', 'SCHEMA',
  'BAGGAGE', 'CONTEXT', 'PROPAGATION', 'HEADER', 'CORRELATION',
  'ANOMALY', 'BASELINE', 'DRIFT', 'NOISE', 'SIGNAL',
  'FLAME', 'PROFILE', 'HEAP', 'THREAD', 'GOROUTINE',
  'LEAK', 'OVERFLOW', 'DEADLOCK', 'RACE', 'MUTEX',
  'SEMAPHORE', 'CHANNEL', 'SOCKET', 'CONNECTION', 'POOL',
  'DNS', 'TCP', 'UDP', 'TLS', 'CERTIFICATE',
  'TOKEN', 'SECRET', 'VAULT', 'ROTATION', 'AUDIT',
  'COMPLIANCE', 'POLICY', 'QUOTA', 'BUDGET', 'COST',
  'TAG', 'LABEL', 'ANNOTATION', 'DIMENSION', 'ATTRIBUTE',
  'AGGREGATE', 'ROLLUP', 'DOWNSAMPLE', 'COMPACT', 'QUERY',
  'RANGE', 'INSTANT', 'RECORDING', 'RULE', 'ALERT',
  'SILENCE', 'INHIBIT', 'GROUP', 'ROUTE', 'RECEIVER',
  'SLACK', 'OPSGENIE', 'PAGERDUTY', 'JIRA', 'WEBHOOK',
  'SYNTHETIC', 'REAL', 'USER', 'MONITOR', 'BROWSER',
  'MOBILE', 'EDGE', 'CDN', 'ORIGIN', 'REGION',
  'ZONE', 'RACK', 'HOST', 'KERNEL', 'EBPF',
  'OTEL', 'COLLECTOR', 'EXPORTER', 'PROCESSOR', 'RESOURCE',
  'INSTRUMENT', 'SPAN', 'BAGGAGE', 'BRIDGE', 'ADAPTER',
  'SCRAPE', 'PUSH', 'PULL', 'FEDERATION', 'REMOTE',
  'WRITE', 'READ', 'STORAGE', 'BLOCK', 'CHUNK',
];

const unique = [...new Set(OBSERVABILITY)];

function validateWordList(words) {
  if (!Array.isArray(words)) return null;
  const cleaned = words
    .map((w) => String(w).trim().toUpperCase())
    .filter((w) => w.length > 0 && w.length <= 30);
  const deduped = [...new Set(cleaned)];
  if (deduped.length < 25) return null;
  return deduped;
}

module.exports = { OBSERVABILITY: unique, validateWordList };
